WITH JOINED_2021 AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE JOINED >= '2021-01-01' AND
          JOINED < '2022-01-01'
)
SELECT DATE_FORMAT(SALES_DATE, '%Y') AS YEAR,
       DATE_FORMAT(SALES_DATE, '%m') AS MONTH,
       COUNT(DISTINCT USER_ID) AS PUCHASED_USERS,
       ROUND(CAST(COUNT(DISTINCT USER_ID) AS DOUBLE) / (SELECT CAST(COUNT(*) AS DOUBLE) FROM JOINED_2021), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE
WHERE USER_ID IN (SELECT USER_ID FROM JOINED_2021)
GROUP BY 1, 2
ORDER BY 1, 2
