WITH CAR_ID_TRUCK AS (
    SELECT CAR_ID, DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = '트럭'
), DISCOUNT_PLAN AS (
    SELECT DURATION_TYPE,
           DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
    UNION ALL
    SELECT '7일 미만' AS DURATION,
           0 AS DISCOUNT_RATE
), TRUCK_RENTAL_HISTORY AS (
    SELECT HISTORY_ID,
           CAR_ID,
           TIMESTAMPDIFF(DAY, START_DATE, END_DATE) + 1 AS DURATION,
           CASE WHEN TIMESTAMPDIFF(DAY, START_DATE, END_DATE) + 1 < 7 THEN '7일 미만'
                WHEN TIMESTAMPDIFF(DAY, START_DATE, END_DATE) + 1 < 30 THEN '7일 이상'
                WHEN TIMESTAMPDIFF(DAY, START_DATE, END_DATE) + 1 < 90 THEN '30일 이상'
                WHEN TIMESTAMPDIFF(DAY, START_DATE, END_DATE) + 1 >= 90 THEN '90일 이상'
           END AS DURATION_TYPE,
           DAILY_FEE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        INNER JOIN CAR_ID_TRUCK
        USING (CAR_ID)
)
SELECT HISTORY_ID,
       FLOOR(DAILY_FEE * DURATION * CAST(100 - COALESCE(DISCOUNT_RATE, 0) AS DOUBLE) / 100.0) AS FEE
FROM TRUCK_RENTAL_HISTORY
    LEFT OUTER JOIN DISCOUNT_PLAN
    USING (DURATION_TYPE)
ORDER BY 2 DESC, 1 DESC
